on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Herumi BLS
        run: go test -tags=bignum_hbls ./...
      - name: Test Kilic BLS
        run: go test -tags=bignum_kilic ./...
      - name: Test Holiman uint256 bignum
        run: go test -tags=bignum_hol256 ./...
      - name: Test Pure bignum
        run: go test -tags=bignum_pure ./...
